export const MAX_PERSONAL_LEAVES_PER_MONTH = 1.5;
export const MAX_PERSONAL_LEAVES_PER_CALENDAR_YEAR = MAX_PERSONAL_LEAVES_PER_MONTH * 12;

export const MAX_SICK_LEAVES_PER_MONTH = null;
export const MAX_SICK_LEAVES_PER_CALENDAR_YEAR = null;
